In [1]:
import pandas as pd
import numpy as np

In [3]:
import warnings
warnings.simplefilter("ignore")

In [18]:
df = pd. read_csv("C:\\Users\\srmve\\OneDrive\\Desktop\\Trip.csv")
df. head ()


Duration        Start date          End date  Start station number  \
0      1012  20-09-2010 11:27  20-09-2010 11:43                 31208   
1        61  20-09-2010 11:41  20-09-2010 11:42                 31209   
2      2690  20-09-2010 12:05  20-09-2010 12:50                 31600   
3      1406  20-09-2010 12:06  20-09-2010 12:29                 31600   
4      1413  20-09-2010 12:10  20-09-2010 12:34                 31100   

                   Start station  End station number  \
0       M St & New Jersey Ave SE               31108   
1                 1st & N St  SE               31209   
2                  5th & K St NW               31100   
3                  5th & K St NW               31602   
4  19th St & Pennsylvania Ave NW               31201   

                     End station Bike number Member type  
0                  4th & M St SW      W00742      Member  
1                 1st & N St  SE      W00032      Member  
2  19th St & Pennsylvania Ave NW      W00993      Member  
3        Park Rd & Holmead Pl NW      W00344      Member  
4                 15th & P St NW      W00883      Member

In [5]:
df.info ()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3571 entries, 0 to 3570
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   user_id                    3571 non-null   object 
 1   submission_count           3571 non-null   int64  
 2   problem_solved             3571 non-null   int64  
 3   contribution               3571 non-null   int64  
 4   country                    2418 non-null   object 
 5   follower_count             3571 non-null   int64  
 6   last_online_time_seconds   3571 non-null   int64  
 7   max_rating                 3571 non-null   float64
 8   rating                     3571 non-null   float64
 9   rank                       3571 non-null   object 
 10  registration_time_seconds  3571 non-null   int64  
dtypes: float64(2), int64(6), object(3)
memory usage: 307.0+ KB


In [6]:
df. describe ()


submission_count  problem_solved  contribution  follower_count  \
count       3571.000000     3571.000000   3571.000000     3571.000000   
mean         299.481098      267.894427      4.102492       46.690563   
std          366.102887      344.139688     16.552256      211.494638   
min            1.000000        0.000000    -64.000000        0.000000   
25%           66.500000       53.000000      0.000000        4.000000   
50%          169.000000      146.000000      0.000000       13.000000   
75%          390.000000      349.000000      0.000000       40.000000   
max         4570.000000     4476.000000    171.000000    10575.000000   

       last_online_time_seconds   max_rating       rating  \
count              3.571000e+03  3571.000000  3571.000000   
mean               1.502680e+09   390.374392   350.165578   
std                5.114850e+06    92.428788   106.592503   
min                1.484237e+09   303.899000     0.000000   
25%                1.502691e+09   317.661000   279.243000   
50%                1.505054e+09   355.791000   329.702000   
75%                1.505551e+09   444.954000   413.417500   
max                1.505595e+09   983.085000   911.124000   

       registration_time_seconds  
count               3.571000e+03  
mean                1.434961e+09  
std                 4.750758e+07  
min                 1.264761e+09  
25%                 1.416323e+09  
50%                 1.449085e+09  
75%                 1.470379e+09  
max                 1.484236e+09

In [7]:
df. isnull (). sum ()

user_id                         0
submission_count                0
problem_solved                  0
contribution                    0
country                      1153
follower_count                  0
last_online_time_seconds        0
max_rating                      0
rating                          0
rank                            0
registration_time_seconds       0
dtype: int64

In [19]:
df=df.drop(['Start date','End date'],axis=1)
df.head()

Duration  Start station number                  Start station  \
0      1012                 31208       M St & New Jersey Ave SE   
1        61                 31209                 1st & N St  SE   
2      2690                 31600                  5th & K St NW   
3      1406                 31600                  5th & K St NW   
4      1413                 31100  19th St & Pennsylvania Ave NW   

   End station number                    End station Bike number Member type  
0               31108                  4th & M St SW      W00742      Member  
1               31209                 1st & N St  SE      W00032      Member  
2               31100  19th St & Pennsylvania Ave NW      W00993      Member  
3               31602        Park Rd & Holmead Pl NW      W00344      Member  
4               31201                 15th & P St NW      W00883      Member

In [20]:
from sklearn. preprocessing import LabelEncoder
label_encoder = LabelEncoder ()
categorical_columns = ['Start station', 'End station', 'Bike number', 'Member type']
df[categorical_columns] = df[categorical_columns]. apply(label_encoder.fit_transform)
df[categorical_columns]

Start station  End station  Bike number  Member type
0                  85           50          614            1
1                  32           33           41            1
2                  52           31          836            1
3                  52           94          282            1
4                  30           21          734            1
...               ...          ...          ...          ...
115592             35           65          716            0
115593             63           18          764            1
115594             93           18          819            1
115595              1           14          946            1
115596              1            1          636            0

[115597 rows x 4 columns]

In [21]:
x = df. iloc [: , :-1]
x

Duration  Start station number  Start station  End station number  \
0           1012                 31208             85               31108   
1             61                 31209             32               31209   
2           2690                 31600             52               31100   
3           1406                 31600             52               31602   
4           1413                 31100             30               31201   
...          ...                   ...            ...                 ...   
115592      2179                 31110             35               31623   
115593       953                 31106             63               31401   
115594       737                 31602             93               31401   
115595       514                 31111              1               31202   
115596     51962                 31111              1               31111   

        End station  Bike number  
0                50          614  
1                33           41  
2                31          836  
3                94          282  
4                21          734  
...             ...          ...  
115592           65          716  
115593           18          764  
115594           18          819  
115595           14          946  
115596            1          636  

[115597 rows x 6 columns]

In [22]:
y = df. iloc [: , -1]
y

0         1
1         1
2         1
3         1
4         1
         ..
115592    0
115593    1
115594    1
115595    1
115596    0
Name: Member type, Length: 115597, dtype: int32

In [23]:
from sklearn. model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split (x, y, random_state=0)

In [25]:
from sklearn. preprocessing import StandardScaler
scaler = StandardScaler ()
x_train = scaler.fit_transform(x_train)
x_test = scaler. transform(x_test)
x_train 

array([[ 0.54640202, -1.40804138, -0.50762432,  1.8909801 ,  0.11621975,
        -1.36635173],
       [-0.32533639, -1.41337456, -0.81044688, -1.36975376,  0.69092124,
        -1.47913197],
       [-0.14892163, -0.28274243, -0.84409383, -0.89702793, -1.10079519,
         1.07843294],
       ...,
       [-0.21022131, -0.16007951, -0.13750786, -0.30074876, -0.35706384,
        -1.51915077],
       [-0.18028425,  1.85052573,  0.77095983,  1.86949256, -0.05281011,
         0.57637894],
       [-0.35277869, -0.35207365,  1.30931104, -0.35983949, -0.93176534,
         0.82740594]])

In [26]:
x_test

array([[-0.36026295, -0.82672581, -1.58432676, -0.20942672,  1.43465259,
        -0.78789821],
       [ 0.00682231, -0.84272532,  0.0307269 , -0.2524018 , -0.76273549,
         0.74736835],
       [-0.28648951, -0.35207365,  1.30931104, -0.88091228,  0.2852496 ,
        -0.93705918],
       ...,
       [-0.12254851, -0.83205898, -0.44033042, -0.26314557, -1.57407878,
         1.63141995],
       [-0.2815    , -0.32540779, -0.40668346, -0.34909572, -1.13460116,
        -1.46457968],
       [-0.16887966, -0.85872483, -1.21421029, -0.29000499, -0.8641534 ,
        -1.01709678]])

In [27]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier ()

In [28]:
model.fit (x_train, y_train)


DecisionTreeClassifier()

In [29]:
y_pred=model. predict(x_test)
y_pred

array([1, 1, 1, ..., 1, 1, 0])

In [31]:
from sklearn. metrics import accuracy_score, classification_report
accuracy = accuracy_score (y_test, y_pred) * 100
print("Accuracy of the model is{:.2f}".format(accuracy))

Accuracy of the model is79.71


In [32]:
from sklearn. metrics import classification_report
class_report = classification_report (y_test, y_pred)
print (f"\nClassification Report:\n{class_report}")



Classification Report:
              precision    recall  f1-score   support

           0       0.52      0.54      0.53      6089
           1       0.88      0.87      0.87     22811

    accuracy                           0.80     28900
   macro avg       0.70      0.70      0.70     28900
weighted avg       0.80      0.80      0.80     28900



In [33]:
new_data = [737, 31110, 63, 31623, 18, 636]
predictions = model. predict([new_data])
print(predictions)


[1]


In [34]:
decoded_predictions = label_encoder. inverse_transform(predictions)
print(decoded_predictions)

['Member']
